/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    GitHubStatItem: typeof import('./src/components/GitHubStatItem.vue')['default']
    LanguageStatItem: typeof import('./src/components/LanguageStatItem.vue')['default']
    Message: typeof import('primevue/message')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
  }
}
