services:
  portfolio:
    build: .
    ports:
      - "4321:4321"
    container_name: "portfolio"
    restart: "unless-stopped"
    environment:
      - VIRTUAL_HOST="bedlinger.at,www.bedlinger.at"
      - LETSENCRYPT_HOST="bedlinger.at,www.bedlinger.at"
      - VIRTUAL_PORT="80"
      - GITHUB_PAT=${PAT_HERE:-default}
    networks:
      - "web"

networks:
  web:
    external: true
