version: '3.8'

services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "portfolio_bedlinger_at"
    restart: "unless-stopped"
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: "bedlinger.at,www.bedlinger.at"
      LETSENCRYPT_HOST: "bedlinger.at,www.bedlinger.at"
      VIRTUAL_PORT: "80"
    networks:
      - "web"

networks:
  web:
    external: true