name: Update Top Languages

on:
  schedule:
    # Run weekly on Sunday at 1:00 AM UTC
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  compute-languages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript script
        run: npx tsc --esModuleInterop --target ES2022 --module NodeNext --moduleResolution NodeNext .github/scripts/computeTopLanguages.ts

      - name: Run language computation script
        run: node .github/scripts/computeTopLanguages.js
        env:
          GITHUB_TOKEN: ${{ secrets.www }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *
          git commit -m "Update top languages data" || echo "No changes to commit"
          git push
